# WhatATheme
markdown: kramdown

# URL of the Site
url: https://levikeay.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: /Project_Site
repository: levikeay/Project_Site
# Title of the Site
title: Levi Keay
# Description of the Site
description: Projects and interests
# URL of Image of the Site
site-image: assets/images/meta.jpg
# Keywords of the Site
site-keywords: Levi Keay, Resume, Physics, Remote Sensing
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/levikeay/Project_Site/master/assets/images/title_imgs/lakemirror.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: levi.keay@gmail.com
facebook_username: 
twitter_username: KeayLevi
instagram_username: 
linkedin_username: levi-keay-172288245?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BVRmA3dV4TRiKlN0jemgfXw%3D%3D
github_username: levikeay
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Levi Keay
# URL for the Image of the Author
author-image: assets/images/title_imgs/Levi1.jpg
# 60 Words About the Author
author-about: |
  Levi is a graduate of the University of British Columbia's physics program. His interests include Remote Sensing/Geomatics, Imaging/Computer Vision, Acoustics, and Python Programming. 
  
  Please feel free to get in touch if you are interested in working together or with any questions regarding my past projects.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: /

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
